### ISSUE TITLE
but how clone all forked by me

### ISSUE THREAD

**Issue by Sandy4321** [rhysd/github-clone-all#1]
great thanks
but how clone all forked by me

**Comment by rhysd** [comment]
https://help.github.com/articles/searching-in-forks/

```
user:Sandy4321 fork:only
```

looks doing that.

**Comment by Sandy4321** [comment]
super and can I use your code on windows
when I use the only python

**Comment by rhysd** [comment]
I put binaries for Windows. Don't they work?

https://github.com/rhysd/github-clone-all/releases

**Comment by Sandy4321** [comment]
great
good job
so it will be like this
github-clone-all.exe   user:Sandy4321 fork:only
but where data will be downloaded, to current folder?
![image](https://user-images.githubusercontent.com/11426119/46919263-dd5c3e00-cfaa-11e8-9d07-fe90790fdd05.png)

**Comment by rhysd** [comment]
please read doc
