### ISSUE TITLE
github-clone-all: command not found

### ISSUE THREAD

**Issue by alecjacobson** [rhysd/github-clone-all#3]
I issued:

```
go get github.com/rhysd/github-clone-all
```

which quietly appeared to succeed. But then if if I try:

```
github-clone-all -extract '(\.vim|vimrc)$' 'language:vim fork:false stars:>1'
```

I get the simple error:
```
-bash: github-clone-all: command not found
```

I think I don't understand how the `go get` command works. (I'm not a usual go user).

**Comment by rhysd** [comment]
you should put $GOPATH/bin to $PATH. anyway, it's not a problem of github-clone-all. Closing
